package db

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Record) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "dest":
			z.Dest, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Dest")
				return
			}
		case "expire":
			z.Expire, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Expire")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Record) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "dest"
	err = en.Append(0x82, 0xa4, 0x64, 0x65, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Dest)
	if err != nil {
		err = msgp.WrapError(err, "Dest")
		return
	}
	// write "expire"
	err = en.Append(0xa6, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Expire)
	if err != nil {
		err = msgp.WrapError(err, "Expire")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Record) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "dest"
	o = append(o, 0x82, 0xa4, 0x64, 0x65, 0x73, 0x74)
	o = msgp.AppendString(o, z.Dest)
	// string "expire"
	o = append(o, 0xa6, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65)
	o = msgp.AppendTime(o, z.Expire)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Record) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "dest":
			z.Dest, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Dest")
				return
			}
		case "expire":
			z.Expire, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Expire")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Record) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Dest) + 7 + msgp.TimeSize
	return
}
